워크샵 개선사항 반영
dns-msa/chaos-engineering pull request #21
Opened 2021-09-07 14:55 UTC by skipio11

소개 및 실습환경 구성변경
EC2 워크샵 수정개선

2021-09-07 14:55 UTC, skipio11 commented
워크샵 컨텐츠는 단순한 파일비교로는 가시성이 떨어져서 develop 브랜치를 만들고 Amplify에 추가로 디플로이를 했습니다.
https://develop.du62hltyts3rv.amplifyapp.com/ko/
내용 검토 부탁드립니다.

2021-09-08 00:42 UTC, Young-ook requested changes
워크샵 Role 이름 변경하는 부분 꼭 확인 부탁드려요.

2021-09-08 00:42 UTC, Young-ook commented on content/10_prerequisites/10_cloud9/01_create_iam.ko.md
> +Create Role 페이지의 **Review**에서 **Role name**을 `fisworkshop-admin-role` 로 입력하고 **Create role** 버튼을 클릭하여 Role을 생성합니다.
이름을 소문자로 통일했을 까요? FIS 만 사용하는 것이 아니라 나중에 Litmus 등을 사용할 수도 있어서 보다 보편적인 ChaosEngineeringWorkshop-Admin 을 유지하면 좋겠습니다.

2021-09-08 00:47 UTC, Young-ook commented on content/20_ec2/20_experiment01/10_hypothesis_ko.md
> +데모 애플리케이션은 recommendation 서비스에 지연이 발생하여도 최종 사용자 경험에 영향을 주지 않거나 1분 이내의 짧은 시간만 영향을 주어야 합니다.
https://github.com/dns-msa/chaos-engineering/blob/main/content/30_eks/20_node_terminate/02_steady_state.ko.md#%EA%B0%80%EC%84%A4-%EC%88%98%EB%A6%BD

여기 내용 보시면 실험 계획표 예제가 있습니다. 참고해 주세요. 같은 내용을 붙여넣기 해주셔도 좋습니다.

2021-09-08 00:55 UTC, Young-ook commented on content/10_prerequisites/_index.ko.md
> -{{% children showhidden="true" %}}
해당 아키텍처 그림과 설명은 EC2 모듈 쪽으로 이동하는 것이군요. 좋습니다! cc: @jjk-dev
👍

2021-09-08 01:05 UTC, skipio11 commented on content/10_prerequisites/10_cloud9/01_create_iam.ko.md
> +Create Role 페이지의 **Review**에서 **Role name**을 `fisworkshop-admin-role` 로 입력하고 **Create role** 버튼을 클릭하여 Role을 생성합니다.
네 저 부분은 변경하시죠. 캡쳐랑 내용이 안맞아서 바꿨는데 말씀하신대로 가시죠.

2021-09-08 04:32 UTC, jjk-dev approved these changes

2021-09-08 05:24 UTC, Young-ook commented on content/10_prerequisites/10_cloud9/01_create_iam.ko.md
> +Create Role 페이지의 **Review**에서 **Role name**을 `fisworkshop-admin-role` 로 입력하고 **Create role** 버튼을 클릭하여 Role을 생성합니다.
넵 변경해 주시고 're-request review'를 해주시면 더블 체크 해 보겠습니다.

2021-09-09 00:46 UTC, skipio11 commented on content/20_ec2/20_experiment01/10_hypothesis_ko.md
> +데모 애플리케이션은 recommendation 서비스에 지연이 발생하여도 최종 사용자 경험에 영향을 주지 않거나 1분 이내의 짧은 시간만 영향을 주어야 합니다.
네 좋은 내용 감사합니다. 다음 PR에 반영하겠습니다.

2021-09-09 00:53 UTC, Young-ook approved these changes
LGTM

2021-09-09 00:53 UTC, merged